import type { Metadata } from "next";
import { Neucha } from "next/font/google";
import "@/styles/globals.scss";
import Header from "@/components/Header/Header";
import Footer from "@/components/Footer/Footer";
import { StorageProvider } from "@/context/StorageContext";
import { Toaster } from "react-hot-toast";

const neucha = Neucha({
  subsets: ["latin"],
  weight: "400",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  modal,
}: Readonly<{
  children: React.ReactNode;
  modal: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${neucha.className}`}>
        <StorageProvider>
          <Toaster />
          <Header />
          {children}
          {modal}
          <Footer />
        </StorageProvider>
      </body>
    </html>
  );
}
