import type { Metadata } from "next";
import { Neucha } from "next/font/google";
import { Toaster } from "react-hot-toast";

//Styles
import "@/styles/globals.scss";

//Components
import Header from "@/components/Header/Header";
import Footer from "@/components/Footer/Footer";

//Context
import { StorageProvider } from "@/context/StorageContext";

//Supabase
import { createClient } from "@/utils/supabase/server";

const neucha = Neucha({
  subsets: ["latin"],
  weight: "400",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  modal,
}: Readonly<{
  children: React.ReactNode;
  modal: React.ReactNode;
}>) {
  const supabase = await createClient();

  const { data } = await supabase.auth.getUser();

  return (
    <html lang="en">
      <body className={`${neucha.className}`}>
        <StorageProvider>
          <Toaster />
          <Header user={data.user} />
          {children}
          {modal}
          <Footer />
        </StorageProvider>
      </body>
    </html>
  );
}
